line_length: 
  warning: 150
  ignores_comments: true
file_length: 500
number_separator:
  minimum_length: 5
large_tuple:
  warning: 3

disabled_rules:
  - todo
  - identifier_name
  - function_body_length
  - cyclomatic_complexity
  - type_name

opt_in_rules:
 - closure_spacing
 - conditional_returns_on_newline
 - empty_count
 - explicit_init
 - overridden_super_call
 - redundant_nil_coalescing
 - nimble_operator
 - closure_end_indentation
 - first_where
 - attributes
 - operator_usage_whitespace
 - prohibited_super_call
 - number_separator
 - object_literal
 - fatal_error_message
