line_length: 150
file_length: 500
number_separator:
  minimum_length: 5
large_tuple:
  warning: 3

disabled_rules:
  - todo
  - variable_name
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - type_name
  - shorthand_operator # waiting next release
  - unused_optional_binding # waiting next release

opt_in_rules:
 - closure_spacing
 - conditional_returns_on_newline
 - empty_count
 - explicit_init
 - overridden_super_call
 - redundant_nil_coalescing
 - nimble_operator
 - closure_end_indentation
 - first_where
 - attributes
 - operator_usage_whitespace
 - prohibited_super_call
 - number_separator