//
//  Created by Tom Baranes on 09/02/16.
//  Copyright © 2016 Jake Lin. All rights reserved.
//

import Foundation

public enum GradientType: String {
  case SunnyDays
  case GreenBeach
  case IntuitivePurple
  case EmeraldWater
  case LemonTwist
  case Horizon
  case RoseWater
  case Frozen
  case MangoPulp
  case BloodyMary
  case Aubergine
  case AquaMarine
  case Sunrise
  case PurpleParadise
  case SeaWeed
  case Pinky
  case Cherry
  case Mojito
  case JuicyOrange
  case Mirage
  case SteelGray
  case Kashmir
  case ElectricViolet
  case VeniceBlue
  case BoraBora
  case Moss
  case ShroomHaze
  case Mystic
  case MidnightCity
  case SeaBlizz
  case Opa
  case Titanium
  case Mantle
  case Dracula
  case Peach
  case Moonrise
  case Clouds
  case Stellar
  case Bourbon
  case CalmDarya
  case Influenza
  case Shrimpy
  case Army
  case Miaka
  case PinotNoir
  case DayTripper
  case Namn
  case BlurryBeach
  case Vasily
  case ALostMemory
  case Petrichor
  case Jonquil
  case SiriusTamed
  case Kyoto
  case MistyMeadow
  case Aqualicious
  case Moor
  case Almost
  case ForeverLost
  case Winter
  case Autumn
  case Candy
  case Reef
  case TheStrain
  case DirtyFog
  case Earthly
  case Virgin
  case Ash
  case ShadowNight
  case Cherryblossoms
  case Parklife
  case DanceToForget
  case Starfall
  case RedMist
  case TealLove
  case NeonLife
  case ManofSteel
  case Amethyst
  case CheerUpEmoKid
  case Shore
  case FacebookMessenger
  case SoundCloud
  case Behongo
  case ServQuick
  case Friday
  case Martini
  case MetallicToad
  case BetweenTheClouds
  case CrazyOrangeI
  case Hersheys
  case TalkingToMiceElf
  case PurpleBliss
  case Predawn
  case EndlessRiver
  case PastelOrangeattheSun
  case Twitch
  case Instagram
  case Flickr
  case Vine
  case Turquoiseflow
  case Portrait
  case VirginAmerica
  case KokoCaramel
  case FreshTurboscent
  case Greentodark
  case Ukraine
  case Curiosityblue
  case DarkKnight
  case Piglet
  case Lizard
  case SagePersuasion
  case BetweenNightandDay
  case Timber
  case Passion
  case ClearSky
  case MasterCard
  case BackToEarth
  case DeepPurple
  case LittleLeaf
  case Netflix
  case LightOrange
  case GreenandBlue
  case Poncho
  case BacktotheFuture
  case Blush
  case Inbox
  case Purplin
  case PaleWood
  case Haikus
  case Pizelex
  case Joomla
  case Christmas
  case MinnesotaVikings
  case MiamiDolphins
  case Forest
  case Nighthawk
  case Superman
  case Suzy
  case DarkSkies
}